randomize();
pick = -1;
play_event = false;
tick = 120;
ii = 0;
over1 = false;
over2 = false;
over3 = false;
over4 = false;
over5 = false;
over6 = false;
over7 = false;
over8 = false;
over9 = false;
global.diplomacy = 0;	